name: Deploy demos to gh-pages
on:
  push:
    branches:
      - main
      - pause-feature
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prepare site folder
        run: |
          rm -rf site || true
          mkdir -p site

          if [ "$GITHUB_REF" = "refs/heads/main" ]; then
            mkdir -p site/v1
            rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='site' ./ site/v1/
          elif [ "$GITHUB_REF" = "refs/heads/pause-feature" ]; then
            mkdir -p site/v2
            rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='site' ./ site/v2/
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            mkdir -p "site/$TAG"
            rsync -av --exclude='.git' --exclude='.github' --exclude='node_modules' --exclude='site' ./ "site/$TAG/"
          else
            echo "Ref não mapeada: $GITHUB_REF"
          fi

          # cria index com links clicáveis
          cat > site/index.html <<'HTML'
          <!doctype html>
          <html>
          <head><meta charset="utf-8"><title>Relationship Timer — Demos</title></head>
          <body>
            <h1>Relationship Timer — Versões</h1>
            <ul>
              <li><a href="./v1/">Versão v1 (sem pausa)</a></li>
              <li><a href="./v2/">Versão v2 (com pausa)</a></li>
            </ul>
            <hr>
            <p>Tags publicadas (ex.: /v1.0.0, /v2.0.0) aparecerão aqui automaticamente.</p>
          </body>
          </html>
          HTML

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./site
